apiVersion: v1
kind: Service
metadata:
  name: comment-service
spec:
  ports:
    - port: 8005
      targetPort: 8005
  selector:
    app: comment-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment-service
  template:
    metadata:
      labels:
        app: comment-service
    spec:
      containers:
      - name: comment-service
        image: cree1116/comment-service:6063f37de5999f068921b2dc1bc17bf7af748b11
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8005
        env:
        - name: POSTGRES_SERVER
          value: "postgres-service"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_SCHEMA
          value: "comment"
        - name: PYTHONPATH
          value: "/app"
