apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: auth-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: cree1116/auth-service:747f09f7a75aebdaaaf200104e2dfc9a21388ed3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: POSTGRES_SERVER
          value: "postgres-service"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "auth_db"
        - name: SECRET_KEY
          value: "k8s-local-secret-key"
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: GOOGLE_CLIENT_ID
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: GOOGLE_CLIENT_SECRET
