apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: cree1116/frontend:29e9146bd8af5dfc7515c0f1a1838a4e7e6d3fe7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
