apiVersion: v1
kind: Service
metadata:
  name: console-frontend
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: console-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: console-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: console-frontend
  template:
    metadata:
      labels:
        app: console-frontend
    spec:
      containers:
      - name: console-frontend
        image: cree1116/console-frontend:41ff899023b340703c5b172e4bb69432f388c362
        imagePullPolicy: Always
        ports:
        - containerPort: 80
