apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  ports:
    - port: 8006
      targetPort: 8006
  selector:
    app: user-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: cree1116/user-service:4d02b5ded6fb176a9c93ce6d4f72af824ed079df
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8006
        env:
        - name: POSTGRES_SERVER
          value: "postgres-service"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_SCHEMA
          value: "user_service"
        - name: SECRET_KEY
          value: "k8s-local-secret-key"
        - name: UPLOAD_DIR
          value: "/app/profiles"
        - name: UPLOAD_SERVICE_URL
          value: "http://upload-service:8001"
        volumeMounts:
        - name: user-storage
          mountPath: /app/profiles
      volumes:
      - name: user-storage
        persistentVolumeClaim:
          claimName: user-pvc
