apiVersion: v1
kind: Service
metadata:
  name: interaction-service
spec:
  ports:
    - port: 8004
      targetPort: 8004
  selector:
    app: interaction-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
    spec:
      containers:
      - name: interaction-service
        image: cree1116/interaction-service:d36caf803ac2caebd73773d88f4c11c07aa30c6e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8004
        env:
        - name: POSTGRES_SERVER
          value: "postgres-service"
        - name: POSTGRES_DB
          value: "auth_db"
        - name: POSTGRES_SCHEMA
          value: "interaction"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: PYTHONPATH
          value: "/app"
        - name: SECRET_KEY
          value: "k8s-local-secret-key"
